name: eeg-image
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - mne>=1.10
  - numpy>=2.3
  - pandas>=2.3
  - matplotlib>=3.10
  - scipy>=1.16
  - pyyaml>=6.0
  - pytest>=8.0
  - jupyter
  - ipython
  - pip
  - pip:
    - mne-qt-browser
