# Component time windows (ms) and default ROI groupings
components:
  P1:
    window_ms: [60, 120]
    rois: [P1]
  N1:
    window_ms: [125, 200]
    rois: [N1_L, N1_R]
  P3b:
    window_ms: [300, 496]
    rois: [P3B]

