dataset:
  root: "data/lab_data_original"
  pattern: "sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ALL"
  min_epochs_per_set: 1
  condition_sets:
    - name: "Increasing 1 to 2"
      conditions: ["12"]
      color: "#2ca02c"  # Green (increasing)
      linestyle: ":"   # dotted
    - name: "Increasing 1 to 3"
      conditions: ["13"]
      color: "#2ca02c"  # Green (decreasing)
      linestyle: "--"    # dashed
components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  formats: ["png"]
  dpi: 300
  colors: ["#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#6a3d9a", "#ffff33"]
  linestyles:
    NC: "-"
    Decrease: ":"
    Increasing: "--"
outputs:
  page: "single"
  plots_dir: "docs/assets/plots/12_13"
  tables_dir: "docs/assets/tables/12_13"
  page: "docs/analysis/12_13.md"
measurement:
  latency: fal     # options: peak | fal
  amplitude: mean  # options: peak | mean (affects reported metrics, not ERP lines)