dataset:
  root: "data/lab_data_original"
  pattern: "sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ACC1"
  min_epochs_per_set: 1
  condition_sets:
    - name: "Increasing 1 to 3"
      conditions: ["13"]
      color: "#02d502"  # Green (increasing)
      linestyle: "-"   # solid
    - name: "Decreasing 3 to 1"
      conditions: ["31"]
      color: "#ef0000"  # Red (decreasing)
      linestyle: "-"    # solid
components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  formats: ["png"]
  dpi: 300
  colors: ["#ef0000", "#2c6dde", "#02d502", "#9900ff", "#9900ff", "#ffff33"]
  linestyles:
    NC: "-"
    Decrease: ":"
    Increasing: "--"
outputs:
  page: "single"
  plots_dir: "docs/assets/plots/13_31_ACC1"
  tables_dir: "docs/assets/tables/13_31_ACC1"
  page: "docs/analysis/13_31_ACC1.md"
measurement:
  latency: fal     # options: peak | fal
  amplitude: mean  # options: peak | mean (affects reported metrics, not ERP lines)