dataset:
  root: "data/hpf_1.5_lpf_35_baseline-on"
  pattern: "sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ALL"
  min_epochs_per_set: 8
  condition_sets:
    - name: "Increasing 2 to 3"
      conditions: ["23"]
      color: "#2ca02c"  # Green (increasing)
      linestyle: "--"   # Dashed
    - name: "Decreasing 3 to 2"
      conditions: ["32"]
      color: "#d62728"  # Red (decreasing)
      linestyle: "--"   # Dashed
    - name: "Cardinality3"
      conditions: ["33"]
      color: "#084594"  # Dark blue
      linestyle: "-"    # Solid

    - name: "Cardinality2"
      conditions: ["22"]
      color: "#9ecae1"  # Light blue
      linestyle: "-"    # Solid

components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  formats: ["png"]
  dpi: 300
  colors: ["#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#6a3d9a", "#ffff33"]
  linestyles:
    NC: "-"
    Decrease: ":"
    Increasing: "--"
outputs:
  page: "single"
  plots_dir: "docs/assets/plots/32_23_22_33"
  tables_dir: "docs/assets/tables/32_23_22_33"
  page: "docs/analysis/32_23_22_33.md"
