dataset:
  root: "data/lab_data_original"
  pattern: "sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ACC1"
  min_epochs_per_set: 1
  condition_sets:
    - name: "3 to 1"
      conditions: ["31"]
      color: "#ef0000"  # Red
      linestyle: "-"    # Solid
    - name: "4 to 2"
      conditions: ["42"]
      color: "#2c6dde"  # Blue
      linestyle: "-"    # Solid
    - name: "5 to 3"
      conditions: ["53"]
      color: "#02d502"  # Green
      linestyle: "-"    # Solid
    - name: "6 to 4"
      conditions: ["64"]
      color: "#9900ff"  # Purple
      linestyle: "-"    # Solid
components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  formats: ["png"]
  dpi: 300
  colors: ["#ef0000", "#2c6dde", "#02d502", "#9900ff", "#9900ff", "#ffff33"]
outputs:
  page: "single"
  plots_dir: "docs/assets/plots/decrease_by_2_ACC1"
  tables_dir: "docs/assets/tables/decrease_by_2_ACC1"
  page: "docs/analysis/decrease_by_2_ACC1.md"
measurement:
  latency: fal     # options: peak | fal
  amplitude: mean  # options: peak | mean (affects reported metrics, not ERP lines)
