dataset:
  root: "data/lab_data_original"
  pattern: "sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ALL"
  min_epochs_per_set: 1
  condition_sets:
    - name: "Cardinality1"
      conditions: ["11"]
      color: "#2c6dde"  # Blue
      linestyle: "-"    # Solid
    - name: "1 to 2"
      conditions: ["12"]
      color: "#02d502"  # green
      linestyle: ":"    # dotted
    - name: "1 to 3"
      conditions: ["13"]
      color: "#02d502"  # green
      linestyle: "--"    # dashed
    - name: "1 to 4"
      conditions: ["14"]
      color: "#02d502"  # green
      linestyle: "-"    # Solid
components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  formats: ["png"]
  dpi: 300
  colors: ["#ef0000", "#2c6dde", "#02d502", "#9900ff", "#9900ff", "#ffff33"]
outputs:
  page: "single"
  plots_dir: "docs/assets/plots/from_1"
  tables_dir: "docs/assets/tables/from_1"
  page: "docs/analysis/from_1.md"
measurement:
  latency: fal     # options: peak | fal
  amplitude: mean  # options: peak | mean (affects reported metrics, not ERP lines)