dataset:
  root: "data"
  pattern: "**/sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ALL"
  min_epochs_per_set: 8
  condition_sets:
    - name: "1 to 2"
      conditions: ["12"]
    - name: "1 to 3"
      conditions: ["13"]
    - name: "1 to 4"
      conditions: ["14"]
components: ["P1", "N1"]  # P3b excluded: peak at epoch edge, FWHM cannot be computed
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  formats: ["png"]
  dpi: 300
outputs:
  page: "single"
  plots_dir: "docs/assets/plots/from1_to_any"
  tables_dir: "docs/assets/tables/from1_to_any"
  page: "docs/analysis/from1_to_any.md"

