dataset:
  root: "data/lab_data_original"
  pattern: "sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ACC1"
  min_epochs_per_set: 1
  condition_sets:
    - name: "4 to 1"
      conditions: ["41"]
      color: "#ef0000"  # Red
      linestyle: "-"    # solid
    - name: "4 to 2"
      conditions: ["42"]
      color: "#ef0000"  # Red
      linestyle: "--"   # dashed
    - name: "4 to 3"
      conditions: ["43"]
      color: "#ef0000"  # Red
      linestyle: ":"    # dotted
    - name: "4 to 5"
      conditions: ["45"]
      color: "#02d502"  # Green
      linestyle: ":"    # dotted
    - name: "4 to 6"
      conditions: ["46"]
      color: "#02d502"  # Green
      linestyle: "--"    # dashed
components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  formats: ["png"]
  dpi: 300
  colors: ["#ef0000", "#2c6dde", "#02d502", "#9900ff", "#9900ff", "#ffff33"]
outputs:
  page: "single"
  plots_dir: "docs/assets/plots/from4_to_any_ACC1"
  tables_dir: "docs/assets/tables/from4_to_any_ACC1"
  page: "docs/analysis/from4_to_any_ACC1.md"
measurement:
  latency: fal     # options: peak | fal
  amplitude: mean  # options: peak | mean (affects reported metrics, not ERP lines)
