dataset:
  root: "data/hpf_1.5_lpf_35_baseline-on"
  pattern: "sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ALL"
  min_epochs_per_set: 8
  condition_sets:
    - name: "1 to 2"
      conditions: ["12"]
    - name: "2 to 3"
      conditions: ["23"]
    - name: "3 to 4"
      conditions: ["34"]
    - name: "4 to 5"
      conditions: ["45"]
    - name: "5 to 6"
      conditions: ["56"]
components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  formats: ["png"]
  dpi: 300
  colors: ["#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#6a3d9a", "#ffff33"]
outputs:
  page: "single"
  plots_dir: "docs/assets/plots/increase_by_1"
  tables_dir: "docs/assets/tables/increase_by_1"
  page: "docs/analysis/increase_by_1.md"
