dataset:
  root: "data/lab_data_original"
  pattern: "sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ACC1"
  min_epochs_per_set: 1
  condition_sets:
    - name: "Small (with 1)"
      conditions: ["12", "13", "23"]
      color: "#9900ff"  # Purple
      linestyle: "-"    # Solid
    - name: "Small (without 1)"
      conditions: ["23"]
      color: "#9900ff"  # Purple
      linestyle: "--"   # Dashed
    - name: "Crossover (with 1)"
      conditions: ["14", "24", "25", "34", "35", "36"]
      color: "#ff7f00"  # Orange
      linestyle: "-"    # Solid
    - name: "Crossover (without 1)"
      conditions: ["24", "25", "34", "35", "36"]
      color: "#ff7f00"  # Orange
      linestyle: "--"   # Dashed
components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  formats: ["png"]
  dpi: 300
  colors: ["#9900ff", "#9900ff", "#ff7f00", "#ff7f00"]
outputs:
  page: "single"
  plots_dir: "docs/assets/plots/increasing_small_crossover_with_and_without_1_ACC1"
  tables_dir: "docs/assets/tables/increasing_small_crossover_with_and_without_1_ACC1"
  page: "docs/analysis/increasing_small_crossover_with_and_without_1_ACC1.md"
measurement:
  latency: fal     # options: peak | fal
  amplitude: mean  # options: peak | mean
