dataset:
  root: "data/lab_data_original"
  pattern: "sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ACC1"
  min_epochs_per_set: 1
  condition_sets:
    - name: "Increasing Small"
      conditions: ["12", "13", "23"]
      color: "#984ea3"  # Purple
      linestyle: "-"    # Solid
    - name: "Increasing Crossover"
      conditions: ["14", "24", "25", "34", "35", "36"]
      color: "#ff7f00"  # Orange
      linestyle: "-"    # Solid
    - name: "Increasing Large"
      conditions: ["45", "46", "56"]
      color: "#4daf4a"  # Green
      linestyle: "-"    # Solid
components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  formats: ["png"]
  dpi: 300
  colors: ["#984ea3", "#ff7f00", "#4daf4a"]
outputs:
  page: "single"
  plots_dir: "docs/assets/plots/increasing_large_vs_small_vs_crossover_ACC1"
  tables_dir: "docs/assets/tables/increasing_large_vs_small_vs_crossover_ACC1"
  page: "docs/analysis/increasing_large_vs_small_vs_crossover_ACC1.md"
measurement:
  latency: fal     # options: peak | fal
  amplitude: mean  # options: peak | mean
