dataset:
  root: "data/lab_data_original"
  pattern: "sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ACC1"
  min_epochs_per_set: 1
  condition_sets:

    - name: "2 to 5"
      conditions: ["25"]
      response: "ACC1"
      color: "#02d502"  # green
      linestyle: "-"    # solid
    - name: "3 to 5"
      conditions: ["35"]
      response: "ACC1"
      color: "#02d502"  # green
      linestyle: "--"    # dashed
    - name: "4 to 5"
      conditions: ["45"]
      response: "ACC1"
      color: "#02d502"  # green
      linestyle: ":"    # dotted
    - name: "5 to 5"
      conditions: ["55"]
      response: "ALL"
      color: "#2c6dde"  # Blue
      linestyle: "-"    # solid
    - name: "6 to 5"
      conditions: ["65"]
      response: "ACC1"
      color: "#ef0000"  # red
      linestyle: ":"    # dotted

components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  formats: ["png"]
  dpi: 300
  colors: ["#2c6dde", "#ff00ff", "#ef0000", "#ff4500", "#ff7f00", "#ffbf00"]

outputs:
  page: "single"
  plots_dir: "docs/assets/plots/landing_on_5_any_preceding_ACC1"
  tables_dir: "docs/assets/tables/landing_on_5_any_preceding_ACC1"
  page: "docs/analysis/landing_on_5_any_preceding_ACC1.md"
measurement:
  latency: fal     # options: peak | fal
  amplitude: mean  # options: peak | mean (affects reported metrics, not ERP lines)