dataset:
  root: "data/lab_data_original"
  pattern: "sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ACC1"
  min_epochs_per_set: 1
  condition_sets:

    - name: "1 to 3"
      conditions: ["13"]
      response: "ACC1"
      color: "#b6e800"  # lime green
      linestyle: "-"    # solid
    - name: "2 to 3"
      conditions: ["23"]
      response: "ACC1"
      color: "#02d502"  # gren
      linestyle: "-"    # solid
    - name: "3 to 3"
      conditions: ["33"]
      response: "ALL"
      color: "#2c6dde"  # Blue
      linestyle: "-"    # solid
    - name: "4 to 3"
      conditions: ["43"]
      response: "ACC1"
      color: "#ff00ff"  # pink
      linestyle: "-"    # solid
    - name: "5 to 3"
      conditions: ["53"]
      response: "ACC1"
      color: "#ef0000"  # red
      linestyle: "-"    # solid
    - name: "6 to 3"
      conditions: ["63"]
      response: "ACC1"
      color: "#9900ff"  # purple
      linestyle: "-"    # solid

components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  formats: ["png"]
  dpi: 300
  colors: ["#2c6dde", "#ff00ff", "#ef0000", "#ff4500", "#ff7f00", "#ffbf00"]

outputs:
  page: "single"
  plots_dir: "docs/assets/plots/landing_on_3_any_preceding_ACC1"
  tables_dir: "docs/assets/tables/landing_on_3_any_preceding_ACC1"
  page: "docs/analysis/landing_on_3_any_preceding_ACC1.md"
measurement:
  latency: fal     # options: peak | fal
  amplitude: mean  # options: peak | mean (affects reported metrics, not ERP lines)