dataset:
  root: "data/lab_data_original_with_primes"
  pattern: "sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"

selection:
  response: "ALL"
  min_epochs_per_set: 1
  condition_sets:
    - name: "4a"
      conditions: ["44"]
      color: "#02d502"  # Green
      linestyle: "-"
      metadata_filters:
        Prime5: ["4a.jpg"]
    - name: "4b"
      conditions: ["44"]
      color: "#9900ff"  # Purple
      linestyle: "-"
      metadata_filters:
        Prime5: ["4b.jpg"]
    - name: "4c"
      conditions: ["44"]
      color: "#ff7f00"  # Orange
      linestyle: "-"
      metadata_filters:
        Prime5: ["4c.jpg"]
    - name: "4d"
      conditions: ["44"]
      color: "#40e0d0"  # Turquoise
      linestyle: "-"
      metadata_filters:
        Prime5: ["4d.jpg"]
    - name: "4e"
      conditions: ["44"]
      color: "#ef0000"  # Red
      linestyle: "-"
      metadata_filters:
        Prime5: ["4e.jpg"]

components: ["P1", "N1", "P3b"]

preprocessing:
  baseline_ms: [-100, 0]

roi:
  min_channels: 4

plots:
  formats: ["png"]
  dpi: 300
  colors: ["#02d502", "#9900ff", "#ff7f00", "#40e0d0", "#ef0000"]

outputs:
  page: "docs/analysis/prime_44.md"
  plots_dir: "docs/assets/plots/prime_44"
  tables_dir: "docs/assets/tables/prime_44"

measurement:
  latency: fal
  amplitude: mean

