dataset:
  root: "data"
  pattern: "**/sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ALL"
  min_epochs_per_set: 8
  condition_sets:
    - name: "Small_Increasing"
      conditions: ["12", "13", "23"]
    - name: "Small_Decreasing"
      conditions: ["32", "31", "21"]
components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  topomap_peak_window_ms: 50
  peak_level: "cohort"
  smoothing:
    method: "moving_average"
    window_ms: 10
  formats: ["png"]
  dpi: 300
  thumb_width_px: 320
  colors: ["#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00", "#ffff33"]
  linestyles:
    NC: "-"
    Decrease: ":"
    Increasing: "--"
outputs:
  page: "single"
  plots_dir: "docs/assets/plots/small_increasing_vs_decreasing"
  tables_dir: "docs/assets/tables/small_increasing_vs_decreasing"
  page: "docs/analysis/small_increasing_vs_decreasing.md"

