dataset:
  root: "data"
  pattern: "**/sub-*_preprocessed-epo.fif"
  montage_sfp: "assets/net/AdultAverageNet128_v1.sfp"
selection:
  response: "ACC1"
  min_epochs_per_set: 8
  condition_sets:
    - name: "Small_Increasing"
      conditions: ["12", "13", "23"]
    - name: "Small_Decreasing"
      conditions: ["32", "31", "21"]
components: ["P1", "N1", "P3b"]
preprocessing:
  baseline_ms: [-100, 0]
roi:
  min_channels: 4
plots:
  topomap_peak_window_ms: 50
  peak_level: "cohort"
  smoothing:
    method: "moving_average"
    window_ms: 10
  formats: ["png"]
  dpi: 300
  thumb_width_px: 320
outputs:
  page: "single"
  plots_dir: "docs/assets/plots/small_increasing_vs_decreasing_ACC1"
  tables_dir: "docs/assets/tables/small_increasing_vs_decreasing_ACC1"
  page: "docs/analysis/small_increasing_vs_decreasing_ACC1.md"

